steps:
    
  - id: 'Compile, package, release'
    name: 'europe-west4-docker.pkg.dev/actin-build/build-registry-docker/actin-build-agent:1.1.3'
    entrypoint: mvn
    args: [ 'test', '-B' ]
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
    env:
      - MAVEN_OPTS=-Dmaven.repo.local=/cache/.m2

options:
  machineType: 'E2_HIGHCPU_8'