steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Populate the maven cache'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - 'gs://actin-build-maven-cache/actin/.m2'
      - '/cache/.m2'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'

  - id: 'Compile, package, release'
    name: 'maven:3.9.7'
    entrypoint: mvn
    args: [ 'test', '-B' ]
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
    env:
      - MAVEN_OPTS=-Dmaven.repo.local=/cache/.m2

  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Update the maven cache'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '/cache/.m2'
      - 'gs://actin-build-maven-cache/actin/.m2/'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'

options:
  machineType: 'E2_HIGHCPU_8'