steps:
    
  - id: 'Compile, package, release'
    name: 'europe-west4-docker.pkg.dev/actin-build/build-registry-docker/actin-build-agent:1.2.0'
    entrypoint: mvn
    args: [ 'test', '-B' ]
    env:
      - MAVEN_OPTS=-Dmaven.repo.local=/.m2/repository

options:
  machineType: 'E2_HIGHCPU_8'