package com.hartwig.actin.report.pdf

import com.hartwig.actin.configuration.ReportIntendedUse
import java.text.MessageFormat
import java.util.Properties

class ReportLabels(private val properties: Properties) {

    val report = Report()
    val sidePanel = SidePanel()
    val footer = Footer()
    val summary = Summary()
    val trialMatching = TrialMatching()
    val efficacyEvidence = EfficacyEvidence()
    val clinicalDetails = ClinicalDetails()
    val molecular = Molecular()
    val misc = Misc()

    inner class Report {
        fun title() = get("report.title")
    }

    inner class SidePanel {
        fun patient() = get("side.panel.patient")
        fun reportDate() = get("side.panel.report.date")
    }

    inner class Footer {
        fun researchDisclaimer() = get("footer.research.disclaimer")
        fun ctgovDisclaimer(date: String) = format("footer.ctgov.disclaimer", date)
        fun attributions() = get("footer.attributions")
    }

    inner class Summary {
        fun title() = get("summary.title")
        fun gender() = get("summary.gender")
        fun birthYear() = get("summary.birth.year")
        fun who() = get("summary.who")
        fun tumor() = get("summary.tumor")
        fun lesions() = get("summary.lesions")
        fun stage() = get("summary.stage")
        fun derivedStages() = get("summary.derived.stages")
    }

    inner class TrialMatching {
        fun title() = get("trial.matching.title")
        fun titleOpenEligible(prefix: String, suffix: String) = format("trial.title.open.eligible", prefix, suffix)
        fun titleOpenMissingMolecular(prefix: String, suffix: String) = format("trial.title.open.missing.molecular", prefix, suffix)
        fun titleClosedEligible(suffix: String) = format("trial.title.closed.eligible", suffix)
        fun titleFilteredEligible(count: String) = format("trial.title.filtered.eligible", count)
        fun titleIneligible(suffix: String) = format("trial.title.ineligible", suffix)
        fun titleNonEvaluable(suffix: String) = format("trial.title.non.evaluable", suffix)
        fun phaseLate(suffix: String) = format("trial.phase.late", suffix)
        fun phaseEarly(suffix: String) = format("trial.phase.early", suffix)
        fun phaseNational() = get("trial.phase.national")
        fun phaseInternational() = get("trial.phase.international")
        fun colTrial() = get("trial.col.trial")
        fun colCohort() = get("trial.col.cohort")
        fun colMolecular() = get("trial.col.molecular")
        fun colSites() = get("trial.col.sites")
        fun colWarnings() = get("trial.col.warnings")
        fun colIneligibilityReasons() = get("trial.col.ineligibility.reasons")
        fun colConfiguration() = get("trial.col.configuration")
        fun footnoteFilteredSuffix() = get("trial.footnote.filtered.suffix")
        fun footnoteChildrensHospital(count: String, suffix: String) = format("trial.footnote.childrens.hospital", count, suffix)
        fun footnoteDutchLung(count: String, suffix: String) = format("trial.footnote.dutch.lung", count, suffix)
        fun footnoteExternalMatched() = get("trial.footnote.external.matched")
        fun footnoteExternalExcluded() = get("trial.footnote.external.excluded")
        fun footnoteNationalMolecular(count: String, suffix: String) = format("trial.footnote.national.molecular", count, suffix)
    }

    inner class EfficacyEvidence {
        fun title() = get("efficacy.title")
        fun patientCharacteristics() = get("efficacy.patient.characteristics")
        fun primaryEndpoints() = get("efficacy.primary.endpoints")
        fun secondaryEndpoints() = get("efficacy.secondary.endpoints")
        fun study() = get("efficacy.study")
        fun molecularRequirements() = get("efficacy.molecular.requirements")
        fun therapies() = get("efficacy.therapies")
        fun none() = get("efficacy.none")
        fun ci() = get("efficacy.ci")
        fun medianOs() = get("efficacy.median.os")
        fun medianPfs() = get("efficacy.median.pfs")
        fun colWhoEcog() = get("efficacy.col.who.ecog")
        fun colPrimaryTumorLocation() = get("efficacy.col.primary.tumor.location")
        fun colMutations() = get("efficacy.col.mutations")
        fun colMetastaticSites() = get("efficacy.col.metastatic.sites")
        fun colPreviousSystemicTherapy() = get("efficacy.col.previous.systemic.therapy")
        fun colPriorTherapies() = get("efficacy.col.prior.therapies")
        fun colAgeMedianRange() = get("efficacy.col.age.median.range")
        fun colSex() = get("efficacy.col.sex")
        fun colRace() = get("efficacy.col.race")
        fun colRegion() = get("efficacy.col.region")
        fun colTimeOfMetastases() = get("efficacy.col.time.of.metastases")
        fun colHrOr() = get("efficacy.col.hr.or")
        fun colPValue() = get("efficacy.col.p.value")
        fun sexMale() = get("efficacy.sex.male")
        fun sexFemale() = get("efficacy.sex.female")
        fun medianFollowUpPfs(months: String) = format("efficacy.median.follow.up.pfs", months)
        fun medianPfsLabel() = get("efficacy.median.pfs.label")
        fun medianOsLabel() = get("efficacy.median.os.label")
        fun chartSurvivalX() = get("efficacy.chart.survival.x")
        fun chartSurvivalY() = get("efficacy.chart.survival.y")
        fun chartShapTitle(treatment: String) = format("efficacy.chart.shap.title", treatment)
        fun chartTreatmentDistributionTitle() = get("efficacy.chart.treatment.distribution.title")
        fun socEligibleTitle() = get("efficacy.soc.eligible.title")
        fun socEfficacyTitle() = get("efficacy.soc.efficacy.title")
        fun socNoOptions() = get("efficacy.soc.no.options")
        fun socNoLiterature() = get("efficacy.soc.no.literature")
        fun socNoResistance() = get("efficacy.soc.no.resistance")
        fun socTreatmentNote() = get("efficacy.soc.treatment.note")
        fun socColTreatment() = get("efficacy.soc.col.treatment")
        fun socColLiteratureEvidence() = get("efficacy.soc.col.literature.evidence")
        fun socColWarnings() = get("efficacy.soc.col.warnings")
        fun socColMutation() = get("efficacy.soc.col.mutation")
        fun socColEvidenceSource() = get("efficacy.soc.col.evidence.source")
        fun socColEvidenceLevel() = get("efficacy.soc.col.evidence.level")
        fun socColFoundInMolecular() = get("efficacy.soc.col.found.in.molecular")
        fun socResistanceTitle() = get("efficacy.soc.resistance.title")
    }

    inner class ClinicalDetails {
        fun title() = get("clinical.title")
        fun summaryTitle() = get("clinical.summary.title")
        fun patientDetailsTitle(date: String) = format("clinical.patient.details.title", date)
        fun medicationTitle() = get("clinical.medication.title")
        fun tumorDetailsTitle(date: String) = format("clinical.tumor.details.title", date)
        fun sectionSystemicHistory() = get("clinical.section.systemic.history")
        fun sectionOtherOncological() = get("clinical.section.other.oncological")
        fun sectionPreviousPrimary() = get("clinical.section.previous.primary")
        fun sectionNonOncological() = get("clinical.section.non.oncological")
        fun keyToxicities() = get("clinical.key.toxicities")
        fun keyInfection() = get("clinical.key.infection")
        fun keyEcg() = get("clinical.key.ecg")
        fun keyQtcf() = get("clinical.key.qtcf")
        fun keyJtc() = get("clinical.key.jtc")
        fun keyLvef() = get("clinical.key.lvef")
        fun keyAllergies() = get("clinical.key.allergies")
        fun keySurgeries() = get("clinical.key.surgeries")
        fun keyMeasurableDisease() = get("clinical.key.measurable.disease")
        fun keyLesions() = get("clinical.key.lesions")
        fun keyNoLesions() = get("clinical.key.no.lesions")
        fun valueInfectionUnknown() = get("clinical.value.infection.unknown")
        fun valueEcgUnknown() = get("clinical.value.ecg.unknown")
        fun colMedication() = get("clinical.col.medication")
        fun colAdminRoute() = get("clinical.col.admin.route")
        fun colStartDate() = get("clinical.col.start.date")
        fun colStopDate() = get("clinical.col.stop.date")
        fun colDosage() = get("clinical.col.dosage")
        fun colFrequency() = get("clinical.col.frequency")
    }

    inner class Molecular {
        fun title() = get("molecular.title")
        fun summaryTitle() = get("molecular.summary.title")
        fun historyTitle() = get("molecular.history.title")
        fun generalTitle() = get("molecular.general.title")
        fun ihcTitle() = get("molecular.ihc.title")
        fun ihcSummaryTitle() = get("molecular.ihc.summary.title")
        fun immunologyTitle() = get("molecular.immunology.title")
        fun immunologyNoHlaAlleles() = get("molecular.immunology.no.hla.alleles")
        fun immunologyHlaTypingNotAvailable() = get("molecular.immunology.hla.typing.not.available")
        fun colType() = get("molecular.col.type")
        fun colDriver() = get("molecular.col.driver")
        fun colTrialsLocations() = get("molecular.col.trials.locations")
        fun colTrialsSource(source: String) = format("molecular.col.trials.source", source)
        fun colBestEvidence(source: String) = format("molecular.col.best.evidence", source)
        fun colResistance(source: String) = format("molecular.col.resistance", source)
        fun colHlaGene() = get("molecular.col.hla.gene")
        fun colTumorCopyNumber() = get("molecular.col.tumor.copy.number")
        fun colMutatedInTumor() = get("molecular.col.mutated.in.tumor")
        fun colEvent() = get("molecular.col.event")
        fun colDescription() = get("molecular.col.description")
        fun colScore() = get("molecular.col.score")
        fun colTreatment() = get("molecular.col.treatment")
        fun treatmentRankingTitle() = get("molecular.treatment.ranking.title")
        fun characteristicsPurity() = get("molecular.characteristics.purity")
        fun characteristicsPloidy() = get("molecular.characteristics.ploidy")
        fun characteristicsTml() = get("molecular.characteristics.tml")
        fun characteristicsTmb() = get("molecular.characteristics.tmb")
        fun characteristicsMs() = get("molecular.characteristics.ms")
        fun characteristicsHr() = get("molecular.characteristics.hr")
        fun characteristicsDpyd() = get("molecular.characteristics.dpyd")
        fun characteristicsUgt1a1() = get("molecular.characteristics.ugt1a1")
        fun evidenceOnLabel() = get("molecular.evidence.on.label")
        fun evidenceOffLabel() = get("molecular.evidence.off.label")
        fun wgsNoSuccessful() = get("molecular.wgs.no.successful")
        fun wgsTissueOriginTitle() = get("molecular.wgs.tissue.origin.title")
        fun wgsTissueOriginTitleWgts() = get("molecular.wgs.tissue.origin.title.wgts")
        fun wgsTmbLabel() = get("molecular.wgs.tmb.label")
        fun wgsTmlTmbLabel() = get("molecular.wgs.tml.tmb.label")
        fun wgsMsStability() = get("molecular.wgs.ms.stability")
        fun wgsHrStatus() = get("molecular.wgs.hr.status")
        fun wgsDriverMutations() = get("molecular.wgs.driver.mutations")
        fun wgsOtherMutations() = get("molecular.wgs.other.mutations")
        fun wgsAmplifiedGenes() = get("molecular.wgs.amplified.genes")
        fun wgsDeletedGenes() = get("molecular.wgs.deleted.genes")
        fun wgsHomozygouslyDisruptedGenes() = get("molecular.wgs.homozygously.disrupted.genes")
        fun wgsGeneFusions() = get("molecular.wgs.gene.fusions")
        fun wgsDriverVirus() = get("molecular.wgs.driver.virus")
        fun wgsPotentialEventsNoHighDriver() = get("molecular.wgs.potential.events.no.high.driver")
        fun wgsPotentialEventsNoTumorDriver() = get("molecular.wgs.potential.events.no.tumor.driver")
        fun wgsNoRelevantAlterations() = get("molecular.wgs.no.relevant.alterations")
        fun wgsInsufficientQuality() = get("molecular.wgs.insufficient.quality")
        fun originTitle() = get("molecular.origin.title")
        fun originTitleWgts() = get("molecular.origin.title.wgts")
        fun originAllBelow10(likelihood: String, cancerType: String) = format("molecular.origin.all.below.10", likelihood, cancerType)
        fun originOtherCohorts(likelihood: String) = format("molecular.origin.other.cohorts", likelihood)
        fun originCombinedScore() = get("molecular.origin.combined.score")
        fun originScoreNote() = get("molecular.origin.score.note")
        fun originSnvTypes() = get("molecular.origin.snv.types")
        fun originSnvGenomic() = get("molecular.origin.snv.genomic")
        fun originDriverGenes() = get("molecular.origin.driver.genes")
        fun originGeneExpression() = get("molecular.origin.gene.expression")
        fun originAltSplice() = get("molecular.origin.alt.splice")
        fun keyDrivers() = get("molecular.key.drivers")
        fun otherDrivers() = get("molecular.other.drivers")
        fun noWgs() = get("molecular.no.wgs")
        fun lowPurity(purity: String) = format("molecular.low.purity", purity)
        fun oldTestVersion(testDate: String, versionDate: String) = format("molecular.old.test.version", testDate, versionDate)
        fun subClonalNote(threshold: String) = format("molecular.sub.clonal.note", threshold)
    }

    inner class Misc {
        fun notAvailable() = get("misc.not.available")
        fun yes() = get("misc.yes")
        fun no() = get("misc.no")
        fun trial() = get("misc.trial")
        fun cohort() = get("misc.cohort")
        fun from() = get("misc.from")
        fun zeroTrials() = get("misc.zero.trials")
    }

    private fun get(key: String): String = properties.getProperty(key) ?: error("Missing label: $key")
    private fun format(key: String, vararg args: Any): String = MessageFormat.format(get(key), *args)

    companion object {
        fun load(intendedUse: ReportIntendedUse): ReportLabels {
            val name = "/labels/${intendedUse.name.lowercase()}.properties"
            val props = Properties().apply {
                ReportLabels::class.java.getResourceAsStream(name)?.bufferedReader(Charsets.UTF_8)?.use(::load)
                    ?: error("Labels not found: $name")
            }
            return ReportLabels(props)
        }
    }
}
