package com.hartwig.actin.treatment.interpretation.single;

public enum FunctionInput {
    NONE,
    ONE_INTEGER,
    TWO_INTEGERS,
    ONE_DOUBLE,
    TWO_DOUBLES,
    ONE_TREATMENT_CATEGORY,
    ONE_TREATMENT_CATEGORY_ONE_STRING,
    ONE_TREATMENT_CATEGORY_MANY_STRINGS,
    ONE_TREATMENT_CATEGORY_ONE_INTEGER,
    ONE_TREATMENT_CATEGORY_ONE_STRING_ONE_INTEGER,
    ONE_TREATMENT_CATEGORY_MANY_STRINGS_ONE_INTEGER,
    ONE_STRING,
    ONE_STRING_ONE_INTEGER,
    ONE_STRING_TWO_INTEGERS,
    TWO_STRINGS,
    ONE_INTEGER_ONE_STRING,
    ONE_INTEGER_MANY_STRINGS,
    ONE_TUMOR_STAGE
}
