package com.hartwig.actin.algo.icd

object IcdConstants {
    const val LEPTOMENINGEAL_METASTASES_CODE = "2D51"
    const val CHRONIC_CANCER_RELATED_PAIN_CODE = "MG30.1"
    const val ACUTE_PAIN_CODE = "MG31"
    const val HYPOKALEMIA_CODE = "5C77"
    const val HYPOMAGNESEMIA_CODE = "5C64.41"
    const val CALCIUM_DEFICIENCY_CODE = "5B5K.1"
    const val ISCHAEMIC_HEART_DISEASES_BLOCK = "BlockL1-BA4"
    const val PULMONARY_HEART_DISEASE_BLOCK = "BlockL1-BB0"
    const val PERICARDITIS_BLOCK = "BlockL1-BB2"
    const val ENDOCARDITIS_BLOCK = "BlockL1-BB4"
    const val HEART_VALVE_DISEASE_BLOCK = "BlockL1-BB6"
    const val DISEASES_OF_CORONARY_ARTERY_BLOCK = "BlockL1-BA8"
    const val DISEASES_OF_THE_MYOCARDIUM_OR_CARDIAC_CHAMBERS_BLOCK = "BlockL1-BC4"
    const val CARDIAC_ARRHYTHMIA_BLOCK = "BlockL1-BC6"
    const val HEART_FAILURE_BLOCK = "BlockL1-BD1"
    const val EYE_DISEASE_CHAPTER = "09"
    const val INTRACRANIAL_HAEMORRHAGE_BLOCK = "BlockL2-8B0"
    const val CEREBRAL_ISCHAEMIA_BLOCK = "BlockL2-8B1"
    const val STROKE_NOS_CODE = "8B20"
    const val DISSECTION_OF_CEREBRAL_ARTERY_CODE = "8B22.0"
    const val HEREDITARY_BLEEDING_DISORDER_BLOCK = "BlockL3-3B1"
    const val HEREDITARY_THROMBOPHILIA_CODE = "3B61.0"
    const val ACUTE_MYOCARDIAL_INFARCT_CODE = "BA41"
    const val DEEP_VEIN_THROMBOSIS_CODE = "BD71"
    const val VENOUS_THROMBOEMBOLISM_CODE = "BD72"
    const val PORTAL_VEIN_THROMBOSIS_CODE = "DB98.3"
    const val SPLENIC_VEIN_THROMBOSIS_CODE = "DB98.4"
    const val CEREBRAL_VENOUS_THROMBOSIS = "8B22.1"
    const val INTRACARDIAC_THROMBOSIS = "BC46"
    const val ACUTE_ARTERIAL_OCCLUSION_CODE = "BD30"
    const val CHOLESTEROL_ATHEROEMBOLISM_CODE = "BD53.4"
    const val PULMONARY_THROMBOEMBOLISM_CODE = "BB00"
    const val CERTAIN_LOWER_RESPIRATORY_TRACT_DISEASES_BLOCK = "BlockL1-CA2"
    const val LUNG_INFECTIONS_BLOCK = "BlockL1-CA4"
    const val LUNG_DISEASES_DUE_TO_EXTERNAL_AGENTS_BLOCK = "BlockL1-CA6"
    const val PNEUMONITIS_BLOCK = "BlockL2-CA7"
    const val LUNG_INTERSTITIAL_DISEASES_BLOCK = "BlockL1-CB0"
    const val PNEUMOTHORAX_CODE = "CB21"
    const val PLEURAL_EFFUSION_CODE = "CB27"
    const val HAEMATOTHORAX_CODE = "CB26"
    const val RESPIRATORY_FAILURE_CODE = "CB41"

    val HEART_DISEASE_LIST = listOf(
        ISCHAEMIC_HEART_DISEASES_BLOCK,
        PULMONARY_HEART_DISEASE_BLOCK,
        PERICARDITIS_BLOCK,
        ENDOCARDITIS_BLOCK,
        HEART_VALVE_DISEASE_BLOCK,
        DISEASES_OF_CORONARY_ARTERY_BLOCK,
        DISEASES_OF_THE_MYOCARDIUM_OR_CARDIAC_CHAMBERS_BLOCK,
        CARDIAC_ARRHYTHMIA_BLOCK,
        HEART_FAILURE_BLOCK
    )

    val STROKE_LIST = listOf(
        INTRACRANIAL_HAEMORRHAGE_BLOCK,
        CEREBRAL_ISCHAEMIA_BLOCK,
        STROKE_NOS_CODE,
        DISSECTION_OF_CEREBRAL_ARTERY_CODE
    )

    val THROMBOEMBOLIC_EVENT_LIST = listOf(
        DEEP_VEIN_THROMBOSIS_CODE,
        VENOUS_THROMBOEMBOLISM_CODE,
        PORTAL_VEIN_THROMBOSIS_CODE,
        SPLENIC_VEIN_THROMBOSIS_CODE,
        CEREBRAL_VENOUS_THROMBOSIS,
        INTRACARDIAC_THROMBOSIS,
        ACUTE_ARTERIAL_OCCLUSION_CODE,
        CHOLESTEROL_ATHEROEMBOLISM_CODE,
        PULMONARY_THROMBOEMBOLISM_CODE
    )

    val ARTERIAL_THROMBOEMBOLIC_EVENT_LIST = listOf(
        ACUTE_MYOCARDIAL_INFARCT_CODE,
        ACUTE_ARTERIAL_OCCLUSION_CODE,
        CHOLESTEROL_ATHEROEMBOLISM_CODE,
        INTRACARDIAC_THROMBOSIS
    )

    val VENOUS_THROMBOEMBOLIC_EVENT_LIST = listOf(
        PULMONARY_THROMBOEMBOLISM_CODE,
        DEEP_VEIN_THROMBOSIS_CODE,
        VENOUS_THROMBOEMBOLISM_CODE,
        PORTAL_VEIN_THROMBOSIS_CODE,
        SPLENIC_VEIN_THROMBOSIS_CODE,
        CEREBRAL_VENOUS_THROMBOSIS
    )

    val RESPIRATORY_COMPROMISE_LIST = listOf(
        CERTAIN_LOWER_RESPIRATORY_TRACT_DISEASES_BLOCK,
        LUNG_INFECTIONS_BLOCK,
        LUNG_DISEASES_DUE_TO_EXTERNAL_AGENTS_BLOCK,
        PNEUMONITIS_BLOCK,
        LUNG_INTERSTITIAL_DISEASES_BLOCK,
        PNEUMOTHORAX_CODE,
        PLEURAL_EFFUSION_CODE,
        HAEMATOTHORAX_CODE,
        RESPIRATORY_FAILURE_CODE
    )
}