package com.hartwig.actin.algo.icd

object IcdConstants {
    const val LEPTOMENINGEAL_METASTASES_CODE = "2D51"
    const val CHRONIC_CANCER_RELATED_PAIN_CODE = "MG30.1"
    const val ACUTE_PAIN_CODE = "MG31"
    const val HYPOKALEMIA_CODE = "5C77"
    const val HYPOMAGNESEMIA_CODE = "5C64.41"
    const val CALCIUM_DEFICIENCY_CODE = "5B5K.1"
    const val ISCHAEMIC_HEART_DISEASES_BLOCK = "BlockL1-BA4"
    const val PULMONARY_HEART_DISEASE_BLOCK = "BlockL1-BB0"
    const val PERICARDITIS_BLOCK = "BlockL1-BB2"
    const val ENDOCARDITIS_BLOCK = "BlockL1-BB4"
    const val HEART_VALVE_DISEASE_BLOCK = "BlockL1-BB6"
    const val DISEASES_OF_CORONARY_ARTERY_BLOCK = "BlockL1-BA8"
    const val DISEASES_OF_THE_MYOCARDIUM_OR_CARDIAC_CHAMBERS_BLOCK = "BlockL1-BC4"
    const val CARDIAC_ARRHYTHMIA_BLOCK = "BlockL1-BC6"
    const val HEART_FAILURE_BLOCK = "BlockL1-BD1"
    const val EYE_DISEASE_CHAPTER = "09"
    const val INTRACRANIAL_HAEMORRHAGE_BLOCK = "BlockL2-8B0"
    const val CEREBRAL_ISCHAEMIA_BLOCK = "BlockL2-8B1"
    const val STROKE_NOS_CODE = "8B20"
    const val DISSECTION_OF_CEREBRAL_ARTERY_CODE = "8B22.0"

    val HEART_DISEASE_LIST = listOf(
        ISCHAEMIC_HEART_DISEASES_BLOCK,
        PULMONARY_HEART_DISEASE_BLOCK,
        PERICARDITIS_BLOCK,
        ENDOCARDITIS_BLOCK,
        HEART_VALVE_DISEASE_BLOCK,
        DISEASES_OF_CORONARY_ARTERY_BLOCK,
        DISEASES_OF_THE_MYOCARDIUM_OR_CARDIAC_CHAMBERS_BLOCK,
        CARDIAC_ARRHYTHMIA_BLOCK,
        HEART_FAILURE_BLOCK
    )

    val STROKE_LIST = listOf(
        INTRACRANIAL_HAEMORRHAGE_BLOCK,
        CEREBRAL_ISCHAEMIA_BLOCK,
        STROKE_NOS_CODE,
        DISSECTION_OF_CEREBRAL_ARTERY_CODE
    )
}