package com.hartwig.actin.algo.icd

object IcdConstants {
    const val LEPTOMENINGEAL_METASTASES_CODE = "2D51"
    const val CHRONIC_CANCER_RELATED_PAIN_CODE = "MG30.1"
    const val ACUTE_PAIN_CODE = "MG31"
    const val HYPOKALEMIA_CODE = "5C77"
    const val HYPOMAGNESEMIA_CODE = "5C64.41"
    const val CALCIUM_DEFICIENCY_CODE = "5B5K.1"
    const val LIVER_DISEASE_BLOCK = "BlockL1-DB9"
    const val IMMUNE_SYSTEM_DISEASE_CHAPTER = "04"
    const val DIGESTIVE_SYSTEM_DISEASE_CHAPTER = "13"
    const val NERVOUS_SYSTEM_DISEASE_CHAPTER = "08"
    const val CIRCULATORY_SYSTEM_DISEASE_CHAPTER = "11"
    const val HYPERTENSIVE_DISEASES_BLOCK = "BlockL1-BA0"
    const val ISCHAEMIC_HEART_DISEASES_BLOCK = "BlockL1-BA4"
    const val PULMONARY_HEART_DISEASE_BLOCK = "BlockL1-BB0"
    const val PERICARDITIS_BLOCK = "BlockL1-BB2"
    const val ENDOCARDITIS_BLOCK = "BlockL1-BB4"
    const val HEART_VALVE_DISEASE_BLOCK = "BlockL1-BB6"
    const val DISEASES_OF_CORONARY_ARTERY_BLOCK = "BlockL1-BA8"
    const val DISEASES_OF_THE_MYOCARDIUM_OR_CARDIAC_CHAMBERS_BLOCK = "BlockL1-BC4"
    const val CARDIAC_ARRHYTHMIA_BLOCK = "BlockL1-BC6"
    const val HEART_FAILURE_BLOCK = "BlockL1-BD1"
    const val CONGESTIVE_HEART_FAILURE_CODE = "BD10"
    const val NYHA_CLASS_1_CODE = "XS3A"
    const val NYHA_CLASS_2_CODE = "XS6B"
    const val NYHA_CLASS_3_CODE = "XS9T"
    const val NYHA_CLASS_4_CODE = "XS9F"
    const val EYE_DISEASE_CHAPTER = "09"
    const val INTRACRANIAL_HAEMORRHAGE_BLOCK = "BlockL2-8B0"
    const val CEREBRAL_ISCHAEMIA_BLOCK = "BlockL2-8B1"
    const val STROKE_NOS_CODE = "8B20"
    const val DISSECTION_OF_CEREBRAL_ARTERY_CODE = "8B22.0"
    const val HEREDITARY_BLEEDING_DISORDER_BLOCK = "BlockL3-3B1"
    const val HEREDITARY_THROMBOPHILIA_CODE = "3B61.0"
    const val ARTERY_DISEASE_BLOCK = "BlockL1-BD3"
    const val VEIN_DISEASE_BLOCK = "BlockL1-BD7"
    const val ACUTE_MYOCARDIAL_INFARCT_CODE = "BA41"
    const val DEEP_VEIN_THROMBOSIS_CODE = "BD71"
    const val VENOUS_THROMBOEMBOLISM_CODE = "BD72"
    const val PORTAL_VEIN_THROMBOSIS_CODE = "DB98.3"
    const val SPLENIC_VEIN_THROMBOSIS_CODE = "DB98.4"
    const val CEREBRAL_VENOUS_THROMBOSIS = "8B22.1"
    const val INTRACARDIAC_THROMBOSIS = "BC46"
    const val ACUTE_ARTERIAL_OCCLUSION_CODE = "BD30"
    const val CHOLESTEROL_ATHEROEMBOLISM_CODE = "BD53.4"
    const val PULMONARY_THROMBOEMBOLISM_CODE = "BB00"
    const val CERTAIN_LOWER_RESPIRATORY_TRACT_DISEASES_BLOCK = "BlockL1-CA2"
    const val CERTAIN_DISEASES_OF_RESPIRATORY_SYSTEM_CODE = "CB40"
    const val LUNG_INFECTIONS_BLOCK = "BlockL1-CA4"
    const val LUNG_DISEASES_DUE_TO_EXTERNAL_AGENTS_BLOCK = "BlockL1-CA6"
    const val PNEUMONITIS_BLOCK = "BlockL2-CA7"
    const val LUNG_INTERSTITIAL_DISEASES_BLOCK = "BlockL1-CB0"
    const val PNEUMOTHORAX_CODE = "CB21"
    const val PLEURAL_EFFUSION_CODE = "CB27"
    const val HAEMATOTHORAX_CODE = "CB26"
    const val RESPIRATORY_FAILURE_CODE = "CB41"
    const val NON_ORGAN_SPECIFIC_AUTOIMMUNE_BLOCK = "BlockL1-4A4"
    const val AUTOINFLAMMATORY_DISORDERS_BLOCK = "BlockL1-4A6"
    const val SARCOIDOSIS_CODE = "4B20"
    const val AUTOIMMUNE_THYROIDITIS_CODE = "5A03.2"
    const val AUTOIMMUNE_MYOPATHY_CODE = "8C81"
    const val AUTOIMMUNE_DISEASE_AUTONOMIC_NERVE_SYSTEM_CODE = "8D82"
    const val AUTOIMMUNE_LIVER_DISEASE_CODE = "DB96"
    const val AUTOIMMUNE_PANCREATITIS_CODE = "DC33"
    const val VASCULITIS_CODE = "4A44"
    const val RHEUMATOID_ARTHRITIS_CODE = "FA20"
    const val DIABETES_MELLITUS_BLOCK = "BlockL2-5A1"
    const val TYPE_1_DIABETES_CODE = "5A10"
    const val MULTIPLE_SCLEROSIS_CODE = "8A40"
    const val PSORIASIS_CODE = "EA90"
    const val INFLAMMATORY_BOWEL_DISEASE_BLOCK = "BlockL1-DD7"
    const val GILBERT_SYNDROME_CODE = "5C58.01"
    const val DISEASES_OF_STOMACH_OR_DUODENUM_BLOCK = "BlockL1-DA4"
    const val DISEASES_OF_SMALL_INTESTINE_BLOCK = "BlockL1-DA9"
    const val DISEASES_OF_LARGE_INTESTINE_BLOCK = "BlockL1-DB3"
    const val KIDNEY_FAILURE_BLOCK = "BlockL2-GB6"
    const val LIVER_CIRRHOSIS_CODE = "DB93.1"
    const val PRESENCE_OF_DEVICE_IMPLANT_OR_GRAFT_BLOCK = "BlockL2-QB5"
    const val LONG_QT_SYNDROME_CODE = "BC65.0"
    const val FAMILY_HISTORY_OF_OTHER_SPECIFIED_HEALTH_PROBLEMS_CODE = "QC6Y"
    const val FAMILY_HISTORY_OF_UNSPECIFIED_HEALTH_PROBLEMS_CODE = "QC6Z"
    const val FAMILY_HISTORY_OF_CARDIOVASCULAR_DISEASE_CODE = "QC67"
    const val EPSTEIN_BARR_MONONUCLEOSIS_CODE = "1D81.0"
    const val ACUTE_HEPATITIS_A_CODE = "1E50.0"
    const val ACUTE_HEPATITIS_B_CODE = "1E50.1"
    const val CHRONIC_HEPATITIS_B_CODE = "1E51.0"
    const val ACUTE_HEPATITIS_C_CODE = "1E50.2"
    const val CHRONIC_HEPATITIS_C_CODE = "1E51.1"
    const val HIV_BLOCK = "BlockL1-1C6"
    const val CYTOMEGALOVIRAL_DISEASE_CODE = "1D82"
    const val TUBERCULOSIS_BLOCK = "BlockL2-1B1"
    const val DRUG_ALLERGY_CODE = "4A85.0"
    const val HISTORY_OF_DRUG_OR_BIOLOGICAL_SUBSTANCE_ALLERGY_CODE = "QC44.2"
    const val ADVERSE_CUTANEOUS_REACTION_TO_MEDICATION_BLOCK = "BlockL1-EH6"
    const val ANAPHYLAXIS_CODE = "4A84"
    const val DRUG_INDUCED_ANAPHYLAXIS_CODE = "4A84.1"
    const val DRUG_HYPERSENSITIVITY_CODE = "4A85.0"
    const val HARMFUL_EFFECTS_OF_DRUGS_CODE = "NE60"
    const val PLATINUM_COMPOUND_CODE = "XM40B7"
    const val TAXANE_CODE = "XM05L1"
    const val PD_L1_PD_1_INHIBITOR_MONOCLONAL_ANTIBODY_OR_ADC_CODE = "XM9ND9"
    const val PEMBROLIZUMAB_CODE = "XM8UG5"
    const val NIVOLUMAB_CODE = "XM6M26"
    const val ATEZOLIZUMAB_CODE = "XM8SU2"
    const val DURVALUMAB_CODE = "XM7NY5"
    const val AVELUMAB_CODE = "XM2065"
    const val CEMIPLIMAB_CODE = "XM9Z80"
    const val MONOCLONAL_ANTIBODY_BLOCK = "http://id.who.int/icd/release/11/mms/252952104"
    const val PRESENCE_OF_TRANSPLANTED_KIDNEY_CODE = "QB63.0"
    const val PRESENCE_OF_TRANSPLANTED_HEART_CODE = "QB63.1"
    const val PRESENCE_OF_TRANSPLANTED_LUNG_CODE = "QB63.2"
    const val PRESENCE_OF_TRANSPLANTED_LIVER_CODE = "QB63.3"
    const val PRESENCE_OF_TRANSPLANTED_BONE_MARROW_CODE = "QB63.6"
    const val PRESENCE_OF_TRANSPLANTED_STEM_CELL_CODE = "QB63.8"
    const val PRESENCE_OF_OTHER_TRANSPLANTED_ORGAN_OR_TISSUE = "QB63.Y"
    const val PRESENCE_OF_TRANSPLANTED_ORGAN_OR_TISSUE_UNSPECIFIED = "QB63.Z"

    val DRUG_ALLERGY_SET = setOf(
        DRUG_ALLERGY_CODE,
        HISTORY_OF_DRUG_OR_BIOLOGICAL_SUBSTANCE_ALLERGY_CODE,
        ADVERSE_CUTANEOUS_REACTION_TO_MEDICATION_BLOCK,
        DRUG_INDUCED_ANAPHYLAXIS_CODE,
        DRUG_HYPERSENSITIVITY_CODE,
        HARMFUL_EFFECTS_OF_DRUGS_CODE
    )

    val PD_L1_PD_1_DRUG_SET = setOf(
        PD_L1_PD_1_INHIBITOR_MONOCLONAL_ANTIBODY_OR_ADC_CODE,
        PEMBROLIZUMAB_CODE,
        NIVOLUMAB_CODE,
        ATEZOLIZUMAB_CODE,
        DURVALUMAB_CODE,
        AVELUMAB_CODE,
        CEMIPLIMAB_CODE
    )

    val HEART_DISEASE_SET = setOf(
        ISCHAEMIC_HEART_DISEASES_BLOCK,
        PULMONARY_HEART_DISEASE_BLOCK,
        PERICARDITIS_BLOCK,
        ENDOCARDITIS_BLOCK,
        HEART_VALVE_DISEASE_BLOCK,
        DISEASES_OF_CORONARY_ARTERY_BLOCK,
        DISEASES_OF_THE_MYOCARDIUM_OR_CARDIAC_CHAMBERS_BLOCK,
        CARDIAC_ARRHYTHMIA_BLOCK,
        HEART_FAILURE_BLOCK
    )

    val STROKE_SET = setOf(
        INTRACRANIAL_HAEMORRHAGE_BLOCK,
        CEREBRAL_ISCHAEMIA_BLOCK,
        STROKE_NOS_CODE,
        DISSECTION_OF_CEREBRAL_ARTERY_CODE
    )

    val THROMBOEMBOLIC_EVENT_SET = setOf(
        DEEP_VEIN_THROMBOSIS_CODE,
        VENOUS_THROMBOEMBOLISM_CODE,
        PORTAL_VEIN_THROMBOSIS_CODE,
        SPLENIC_VEIN_THROMBOSIS_CODE,
        CEREBRAL_VENOUS_THROMBOSIS,
        INTRACARDIAC_THROMBOSIS,
        ACUTE_ARTERIAL_OCCLUSION_CODE,
        CHOLESTEROL_ATHEROEMBOLISM_CODE,
        PULMONARY_THROMBOEMBOLISM_CODE
    )

    val ARTERIAL_THROMBOEMBOLIC_EVENT_SET = setOf(
        ACUTE_MYOCARDIAL_INFARCT_CODE,
        ACUTE_ARTERIAL_OCCLUSION_CODE,
        CHOLESTEROL_ATHEROEMBOLISM_CODE,
        INTRACARDIAC_THROMBOSIS
    )

    val VENOUS_THROMBOEMBOLIC_EVENT_SET = setOf(
        PULMONARY_THROMBOEMBOLISM_CODE,
        DEEP_VEIN_THROMBOSIS_CODE,
        VENOUS_THROMBOEMBOLISM_CODE,
        PORTAL_VEIN_THROMBOSIS_CODE,
        SPLENIC_VEIN_THROMBOSIS_CODE,
        CEREBRAL_VENOUS_THROMBOSIS
    )

    val RESPIRATORY_COMPROMISE_SET = setOf(
        CERTAIN_LOWER_RESPIRATORY_TRACT_DISEASES_BLOCK,
        LUNG_INFECTIONS_BLOCK,
        LUNG_DISEASES_DUE_TO_EXTERNAL_AGENTS_BLOCK,
        PNEUMONITIS_BLOCK,
        LUNG_INTERSTITIAL_DISEASES_BLOCK,
        PNEUMOTHORAX_CODE,
        PLEURAL_EFFUSION_CODE,
        HAEMATOTHORAX_CODE,
        RESPIRATORY_FAILURE_CODE,
        CERTAIN_DISEASES_OF_RESPIRATORY_SYSTEM_CODE
    )

    val AUTOIMMUNE_DISEASE_SET = setOf(
        NON_ORGAN_SPECIFIC_AUTOIMMUNE_BLOCK,
        AUTOINFLAMMATORY_DISORDERS_BLOCK,
        SARCOIDOSIS_CODE,
        AUTOIMMUNE_THYROIDITIS_CODE,
        AUTOIMMUNE_MYOPATHY_CODE,
        AUTOIMMUNE_DISEASE_AUTONOMIC_NERVE_SYSTEM_CODE,
        AUTOIMMUNE_LIVER_DISEASE_CODE,
        AUTOIMMUNE_PANCREATITIS_CODE,
        VASCULITIS_CODE,
        RHEUMATOID_ARTHRITIS_CODE,
        TYPE_1_DIABETES_CODE,
        MULTIPLE_SCLEROSIS_CODE,
        PSORIASIS_CODE,
        INFLAMMATORY_BOWEL_DISEASE_BLOCK
    )

    val POSSIBLE_ABSORPTION_DIFFICULTIES_SET = setOf(
        DISEASES_OF_LARGE_INTESTINE_BLOCK,
        DISEASES_OF_SMALL_INTESTINE_BLOCK,
        DISEASES_OF_STOMACH_OR_DUODENUM_BLOCK
    )

    val TRANSPLANTATION_SET = setOf(
        PRESENCE_OF_TRANSPLANTED_KIDNEY_CODE,
        PRESENCE_OF_TRANSPLANTED_HEART_CODE,
        PRESENCE_OF_TRANSPLANTED_LUNG_CODE,
        PRESENCE_OF_TRANSPLANTED_LIVER_CODE,
        PRESENCE_OF_TRANSPLANTED_BONE_MARROW_CODE,
        PRESENCE_OF_TRANSPLANTED_STEM_CELL_CODE,
        PRESENCE_OF_OTHER_TRANSPLANTED_ORGAN_OR_TISSUE,
        PRESENCE_OF_TRANSPLANTED_ORGAN_OR_TISSUE_UNSPECIFIED
    )
}

