package com.hartwig.actin.algo.ckb.json

import com.fasterxml.jackson.annotation.JsonProperty

data class CkbPatientPopulation(
    val id: Int,
    @JsonProperty("is_control") val isControl: Boolean,
    @JsonProperty("group_name") val groupName: String,
    @JsonProperty("n_patients") val nPatients: String,
    @JsonProperty("n_female") val nFemale: String?,
    @JsonProperty("n_male") val nMale: String?,
    @JsonProperty("age_min") val ageMin: String,
    @JsonProperty("age_max") val ageMax: String,
    @JsonProperty("median_age") val medianAge: String,
    @JsonProperty("n_65_or_older") val n65OrOlder: String?,
    @JsonProperty("n_ecog_0") val nEcog0: String?,
    @JsonProperty("n_ecog_1") val nEcog1: String?,
    @JsonProperty("n_ecog_2") val nEcog2: String?,
    @JsonProperty("n_ecog_3") val nEcog3: String?,
    @JsonProperty("n_ecog_4") val nEcog4: String?,
    @JsonProperty("n_ecog_0_to_1") val nEcog0to1: String?,
    @JsonProperty("n_ecog_1_to_2") val nEcog1to2: String?,
    @JsonProperty("highest_ecog_score") val highestEcogScore: Int,
    @JsonProperty("n_localization_primary_tumor") val nLocalizationPrimaryTumor: String?,
    @JsonProperty("other_mutations") val otherMutations: String,
    @JsonProperty("n_primary_tumor_removed_complete") val nPrimaryTumorRemovedComplete: String?,
    @JsonProperty("n_primary_tumor_removed_partial") val nPrimaryTumorRemovedPartial: String?,
    @JsonProperty("n_primary_tumor_removed") val nPrimaryTumorRemoved: String?,
    @JsonProperty("n_previous_lines_of_therapy_1") val nPreviousLinesOfTherapy1: String?,
    @JsonProperty("n_previous_lines_of_therapy_2") val nPreviousLinesOfTherapy2: String?,
    @JsonProperty("n_previous_lines_of_therapy_3") val nPreviousLinesOfTherapy3: String?,
    @JsonProperty("n_previous_lines_of_therapy_4_or_more") val nPreviousLinesOfTherapy4OrMore: String?,
    @JsonProperty("n_prior_systemic_therapy") val nPriorSystemicTherapy: String?,
    @JsonProperty("n_stage_description") val nStageDescription: String?,
    @JsonProperty("n_mutation_status") val nMutationStatus: String?,
    @JsonProperty("n_high_microsatellite_stability") val nHighMicrosatelliteStability: String?,
    @JsonProperty("median_follow_up_for_survival") val medianFollowUpForSurvival: String?,
    @JsonProperty("median_follow_up_for_progression_free_survival") val medianFollowUpForProgressionFreeSurvival: String?,
    @JsonProperty("median_follow_up_for_randomization_to_data_cut_off") val medianFollowUpForRandomizationToDataCutOff: String?,
    @JsonProperty("metastatic_sites") val metastaticSites: String?,
    @JsonProperty("time_of_metastases") val timeOfMetastases: String?,
    val therapy: CkbTherapyOfPopulation?,
    @JsonProperty("analysis_groups") val analysisGroups: List<CkbAnalysisGroup>,
    @JsonProperty("efficacy_evidence") val efficacyEvidence: List<CkbEfficacyEvidence>,
    @JsonProperty("therapy_details") val therapyDetails: String?,
    @JsonProperty("prior_therapies") val priorTherapies: String,
    val race: String,
    val region: String,
    val notes: String?
)
