package com.hartwig.actin.clinical.feed.emc.questionnaire

internal enum class QuestionnaireKey {
    TREATMENT_HISTORY_CURRENT_TUMOR,
    OTHER_ONCOLOGICAL_HISTORY,
    SECONDARY_PRIMARY,
    NON_ONCOLOGICAL_HISTORY,
    PRIMARY_TUMOR_LOCATION,
    PRIMARY_TUMOR_TYPE,
    BIOPSY_LOCATION,
    STAGE,
    HAS_MEASURABLE_DISEASE,
    HAS_CNS_LESIONS,
    HAS_BRAIN_LESIONS,
    HAS_BONE_LESIONS,
    HAS_LIVER_LESIONS,
    OTHER_LESIONS,
    IHC_TEST_RESULTS,
    PDL1_TEST_RESULTS,
    WHO_STATUS,
    UNRESOLVED_TOXICITIES,
    SIGNIFICANT_CURRENT_INFECTION,
    SIGNIFICANT_ABERRATION_LATEST_ECG,
    COMPLICATIONS,
    FAMILY_HISTORY
}