package com.hartwig.actin.clinical.datamodel;

public enum TreatmentCategory {
    CHEMOTHERAPY,
    RADIOTHERAPY,
    CHEMORADIOTHERAPY,
    TARGETED_THERAPY,
    IMMUNOTHERAPY,
    HORMONE_THERAPY,
    ANTIVIRAL_THERAPY,
    SUPPORTIVE_TREATMENT,
    SURGERY,
    STEM_CELL_TRANSPLANTATION,
    TRIAL,
    VACCINE,
    CAR_T
}
