package com.hartwig.actin.soc.datamodel

enum class TreatmentComponent {
    BEVACIZUMAB, CAPECITABINE, CETUXIMAB, ENCORAFENIB, FLUOROURACIL, IRINOTECAN, OXALIPLATIN, PANITUMUMAB, PEMBROLIZUMAB, TIPIRACIL, TRIFLURIDINE
}