package com.hartwig.actin.clinical.feed.questionnaire;

enum QuestionnaireKey {
    TREATMENT_HISTORY_CURRENT_TUMOR,
    OTHER_ONCOLOGICAL_HISTORY,
    NON_ONCOLOGICAL_HISTORY,
    PRIMARY_TUMOR_LOCATION,
    PRIMARY_TUMOR_TYPE,
    BIOPSY_LOCATION,
    STAGE,
    HAS_MEASURABLE_DISEASE,
    HAS_CNS_LESIONS,
    HAS_BRAIN_LESIONS,
    HAS_BONE_LESIONS,
    HAS_LIVER_LESIONS,
    OTHER_LESIONS,
    MOLECULAR_TESTS,
    WHO_STATUS,
    UNRESOLVED_TOXICITIES,
    SIGNIFICANT_CURRENT_INFECTION,
    SIGNIFICANT_ABERRATION_LATEST_ECG,
    COMPLICATIONS
}
