package com.hartwig.actin.datamodel.clinical

import com.hartwig.actin.datamodel.Displayable

enum class LabMeasurement(val code: String, val display: String, val defaultUnit: LabUnit) : Displayable {
    URINE_VOLUME_24H("24UVOL", "24-hour volume urine", LabUnit.MILLILITERS),
    URINE_VOLUME_24H_ENDO("24UVOL_ENDO", "24-hour volume urine for endocrinology", LabUnit.MILLILITERS),
    URINE_VOLUME_24H_SUB("24UVOL_SUB", "24-hour volume urine for solid ", LabUnit.MILLILITERS),
    THREE__MT("3_MT", "3-Methoxytyramine", LabUnit.NANOMOLES_PER_LITER),
    FIVE_HIAA_24U("5HIAA_24U", "5-HIAA per 24-hour urine", LabUnit.NONE),
    FIVE_HIAA_CREA("5HIAA_CREA", "5-HIAA per creatinine", LabUnit.MILLIMOLES_PER_MOLE),
    FIVE_HIAA_U("5HIAA_U", "5-HIAA per urine ", LabUnit.MICROMOLES_PER_LITER),
    A1M_CREA_R_U("A1M_CREA_R_U", "Alpha1-microglobulin/creatinine ratio", LabUnit.GRAMS_PER_MOLE),
    A1M_U("A1M_U", "Alpha1-microglobulin", LabUnit.MILLIGRAMS_PER_LITER),
    AAT("AAT", "Alpha 1 antitrypsin", LabUnit.GRAMS_PER_LITER),
    ACE_2("ACE_2", "Angiotensin-converting enzyme 2", LabUnit.UNITS_PER_LITER),
    ADRENOCORTICOTROPIC_HORMONE("ACTH", "Adrenocorticotropic hormone", LabUnit.PICOMOLES_PER_LITER),
    ALPHA_FETOPROTEIN("AFP", "Alpha-fetoprotein", LabUnit.NANOGRAMS_PER_MILLILITER),
    AG("AG", "Anion Gap", LabUnit.MILLIMOLES_PER_LITER),
    ALANINE_AMINOTRANSFERASE("ALAT", "ALAT", LabUnit.UNITS_PER_LITER),
    ALBUMIN("ALB", "Albumin", LabUnit.GRAMS_PER_LITER),
    ALB_CREA_R("ALB_CREA_R", "Albumin/Creatinine ratio", LabUnit.GRAMS_PER_MOLE),
    ALB_F_C("ALB_F_C", "Albumin fraction C", LabUnit.GRAMS_PER_LITER),
    ALB_U("ALB_U", "Albumin in urine", LabUnit.GRAMS_PER_LITER),
    ALKALINE_PHOSPHATASE("ALP", "Alkaline phosphatase", LabUnit.UNITS_PER_LITER),
    ALPHA1_F_C("ALPHA1_F_C", "Alpha1 fraction C", LabUnit.GRAMS_PER_LITER),
    ALPHA2_F_C("ALPHA2_F_C", "Alpha 2 fraction C", LabUnit.GRAMS_PER_LITER),
    AMYLASE("AMYL", "Amylase", LabUnit.UNITS_PER_LITER),
    AND("AND", "Androstenedione", LabUnit.NANOMOLES_PER_LITER),
    APOB("APOB", "Apolipoprotein B", LabUnit.GRAMS_PER_LITER),
    ACTIVATED_PARTIAL_THROMBOPLASTIN_TIME("APTT", "Activated partial thromboplastin time", LabUnit.SECONDS),
    APTT_R("APTT_R", "APTT ratio", LabUnit.NONE),
    ASPARTATE_AMINOTRANSFERASE("ASAT", "ASAT", LabUnit.UNITS_PER_LITER),
    B2M("B2M", "b2-Microglobuline", LabUnit.MILLIGRAMS_PER_LITER),
    BASOPHIL_GRANULOCYTES_ABSOLUTE("BASO_ABS", "Basophil granulocytes absolute", LabUnit.BILLIONS_PER_LITER),
    BASO_PCT("BASO_PCT", "Basophil granulocytes percentage", LabUnit.PERCENTAGE),
    BCELL_PCT("BCELL_PCT", "Percentage B-cells", LabUnit.PERCENTAGE_OF_LEUKOCYTES),
    BASE_EXCESS_BLOOD_GASS("BE_BG", "Base excess (blood gas)", LabUnit.MILLIMOLES_PER_LITER),
    BETA_F_C("BETA_F_C", "Beta fraction C", LabUnit.GRAMS_PER_LITER),
    NT_PRO_BNP("BNP", "NT-pro-BNP", LabUnit.PICOMOLES_PER_LITER),
    BP3("BP3", "IGF-BP3", LabUnit.MILLIGRAMS_PER_LITER),
    CARBOHYDRATE_ANTIGEN_125("C125", "CA 125", LabUnit.KILOUNITS_PER_LITER),
    CARBOHYDRATE_ANTIGEN_15_3("C153", "CA 15.3", LabUnit.KILOUNITS_PER_LITER),
    CARBOHYDRATE_ANTIGEN_19_9("C199", "CA 19.9", LabUnit.KILOUNITS_PER_LITER),
    CALCIUM("Ca", "Calcium", LabUnit.MILLIMOLES_PER_LITER),
    CORRECTED_CALCIUM("Ca_C", "Calcium corrected", LabUnit.MILLIMOLES_PER_LITER),
    CAL("CAL", "Calcitonin", LabUnit.NANOGRAMS_PER_LITER),
    CALP("CALP", "Weight calprotectine Buhlman", LabUnit.GRAMS),
    CALPBUL_FE("CALPBUL_FE", "Calprotectine Buhlman", LabUnit.MICROGRAMS_PER_GRAM),
    CALPBUL_FE_M("CALPBUL_FE_M", "Calprot Buhman measure", LabUnit.MICROGRAMS_PER_GRAM),
    CCP_AB("CCP_AB", "CCP antibodies", LabUnit.UNITS_PER_MILLILITER),
    CD4("CD4", "CD4+T-Cells", LabUnit.MILLIONS_PER_LITER),
    CD4_CD8_R("CD4_CD8_R", "CD4/CD8 ratio", LabUnit.NONE),
    CD4_POSITIVE_CELLS("CD4_PCT", "Percentage CD4+ T-cells", LabUnit.CELLS_PER_MICROLITER),
    CD8("CD8", "CD8+T-Cells", LabUnit.MILLIONS_PER_LITER),
    CD8_PCT("CD8_PCT", "Percentage CD8+ T-cells", LabUnit.PERCENTAGE_OF_T_CELLS),
    CARCINOEMBRYONIC_ANTIGEN("CEA", "Carcinoembryonic antigen", LabUnit.MICROGRAMS_PER_LITER),
    CERU_P("CERU_P", "Ceruloplasmin", LabUnit.GRAMS_PER_LITER),
    CgA("CgA", "Chromogranin A", LabUnit.NANOGRAMS_PER_MILLILITER),
    CHOL("CHOL", "Cholesterol", LabUnit.MILLIMOLES_PER_LITER),
    CHOL_HDL_R("CHOL_HDL_R", "Cholesterol-HDL ratio", LabUnit.NONE),
    CK("CK", "Creatine Kinase", LabUnit.UNITS_PER_LITER),
    EGFR_CKD_EPI("CKD_EPIeGFR", "CKD-EPI eGFR", LabUnit.MILLILITERS_PER_MINUTE),
    CKMB("CKMB", "CKMB mass", LabUnit.MICROGRAMS_PER_LITER),
    Cl("Cl", "Chloride", LabUnit.MILLIMOLES_PER_LITER),
    Cl_U("Cl_U", "Chloride in urine", LabUnit.MILLIMOLES_PER_LITER),
    COHb("COHb", "Carboxyhemoglobin (blood gas)", LabUnit.NONE),
    COHb_F("COHb_F", "COHB blood gas (F)", LabUnit.NONE),
    COHb_PCT("COHb_PCT", "COHB blood gas (%)", LabUnit.PERCENTAGE),
    CORTISOL("COR", "Cortisol", LabUnit.NANOMOLES_PER_LITER),
    COR_FREE("COR_FREE", "Free cortisol", LabUnit.NANOMOLES_PER_DAY),
    COR_U("COR_U", "Cortisol in urine", LabUnit.NANOMOLES_PER_LITER),
    CPE("CPE", "C-Peptide", LabUnit.NANOMOLES_PER_LITER),
    CREATININE("CREA", "Creatinine", LabUnit.MICROMOLES_PER_LITER),
    CREATININE_CLEARANCE_CG("CGCRCL", "Creatinine clearance (Cockcroft-Gault)", LabUnit.NONE),
    CREA_24U("CREA_24U", "Creatinine per 24-hour urine", LabUnit.MILLIMOLES_PER_DAY),
    CREA_CLEAR("CREA_CLEAR", "Urine creatinine-clearance", LabUnit.MILLILITERS_PER_MINUTE),
    CREA_U("CREA_U", "Creatinine per urine", LabUnit.MILLIMOLES_PER_LITER),
    CRP("CRP", "C-reactive protein", LabUnit.MILLIGRAMS_PER_LITER),
    CT_ALB("CT_ALB", "ct_Albumine", LabUnit.NONE),
    CYFRA("CYFRA", "Cyfra 21.1", LabUnit.MICROGRAMS_PER_LITER),
    CyIgK_CyIgL_R("CyIgK_CyIgL_R", "CyIgK/CyIgL ratio", LabUnit.NONE),
    DIRECT_BILIRUBIN("DBIL", "Direct bilirubin", LabUnit.MICROMOLES_PER_LITER),
    DDIMER("DDIM", "D-dimer", LabUnit.MILLIGRAMS_PER_LITER),
    DEV_POP_PCT("DEV_POP_PCT", "% deviating population", LabUnit.PERCENTAGE_OF_LEUKOCYTES),
    DHEA("DHEA", "DHEA", LabUnit.NANOMOLES_PER_LITER),
    DHEAS("DHEAS", "DHEA sulfate", LabUnit.MICROMOLES_PER_LITER),
    DNA_CONC_A("DNA_CONC_A", "DNA concentration A", LabUnit.MICROGRAMS_PER_MICROLITER),
    DNA_CONC_B("DNA_CONC_B", "DNA concentration B", LabUnit.MICROGRAMS_PER_MICROLITER),
    DOC("DOC", "11-Desoxycortisol", LabUnit.NANOMOLES_PER_LITER),
    DUM_PPT("DUM_PPT", "PPT tube", LabUnit.PICOMOLES_PER_LITER),
    E2("E2", "Estradiol", LabUnit.PICOMOLES_PER_LITER),
    EDNA("EDNA", "dsDNA antibodies", LabUnit.INTERNATIONAL_UNITS_PER_MILLILITER),
    EO_ABS("EO_ABS", "Eosinophil granulocytes absolute", LabUnit.BILLIONS_PER_LITER),
    EO_LQ("EO_LQ", "Eosinophil granulocytes LQ", LabUnit.MILLIONS_PER_LITER),
    EO_PCT("EO_PCT", "Eosinophil granulocytes percentage", LabUnit.PERCENTAGE),
    ER("ER", "Erythrocytes", LabUnit.TRILLIONS_PER_LITER),
    ER_LQ("ER_LQ", "Erythrocytes in liquor", LabUnit.TRILLIONS_PER_LITER),
    ERFM("ERFM", "Rheumatoid factors", LabUnit.INTERNATIONAL_UNITS_PER_MILLILITER),
    ERYTHROB_ABS("ERYTHROB_ABS", "Erythroblasts absolute", LabUnit.BILLIONS_PER_LITER),
    ESR("ESR", "Erythrocyte sedimentation rate", LabUnit.MILLIMETERS_PER_HOUR),
    EVEW("EVEW", "Everolimus", LabUnit.MICROGRAMS_PER_LITER),
    F8S("F8S", "FVIII act", LabUnit.UNITS_PER_MILLILITER),
    FBGC("FBGC", "Fibrinogen Clauss", LabUnit.GRAMS_PER_LITER),
    Fe("Fe", "Iron", LabUnit.MICROMOLES_PER_LITER),
    FER("FER", "Ferritin", LabUnit.MICROGRAMS_PER_LITER),
    FK_FL_R("FK_FL_R", "Ratio Free Kappa / Free Lambda", LabUnit.NONE),
    FKAP("FKAP", "Free Kappa", LabUnit.MILLIGRAMS_PER_LITER),
    FLAM("FLAM", "Free Lambda", LabUnit.MILLIGRAMS_PER_LITER),
    FOLA("FOLA", "Folic acid", LabUnit.NANOMOLES_PER_LITER),
    FPSA("FPSA", "Free PSA", LabUnit.MICROGRAMS_PER_LITER),
    FRL("FRL", "Freeze number leukemia", LabUnit.NONE),
    FSH("FSH", "Follicle-stimulating hormone", LabUnit.UNITS_PER_LITER),
    FREE_T3("FT3", "Free T3", LabUnit.PICOMOLES_PER_LITER),
    FREE_T4("FT4", "Free T4", LabUnit.PICOMOLES_PER_LITER),
    FV("FV", "Factor V", LabUnit.UNITS_PER_MILLILITER),
    GAMMA_F_C("GAMMA_F_C", "Gamma fraction C", LabUnit.GRAMS_PER_LITER),
    GAS("GAS", "Gastrin", LabUnit.NANOGRAMS_PER_LITER),
    EGFR_MDRD("EGFR_MDRD", "Estimated GFR (MDRD)", LabUnit.NONE),
    GGT("GGT", "Gamma-glutamyltransferase", LabUnit.UNITS_PER_LITER),
    GLA("GLA", "Mprot IgG-L1", LabUnit.GRAMS_PER_LITER),
    GLUC("GLUC", "Glucose", LabUnit.MILLIMOLES_PER_LITER),
    GLUC_LQ("GLUC_LQ", "Glucose in liquor", LabUnit.MILLIMOLES_PER_LITER),
    GRAN_LQ("GRAN_LQ", "Granulocytes in liquor", LabUnit.BILLIONS_PER_LITER),
    GRH("GRH", "Growth hormone", LabUnit.MICROGRAMS_PER_LITER),
    HAPTO("HAPTO", "Haptoglobin", LabUnit.GRAMS_PER_LITER),
    HEMOGLOBIN("Hb", "Hemoglobin", LabUnit.MILLIMOLES_PER_LITER),
    HbA0("HbA0", "Hemoglobin A0", LabUnit.PERCENTAGE),
    HbA1c("HbA1c", "Hemoglobin A1c", LabUnit.MILLIMOLES_PER_MOLE),
    HbE("HbE", "Hemoglobin E", LabUnit.PERCENTAGE),
    HbF_F("HbF_F", "HbF blood gas (F)", LabUnit.NONE),
    HbF_PCT("HbF_PCT", "HbF blood gas (%)", LabUnit.PERCENTAGE),
    HCG_AND_BETA_HCG("HCG", "HGC + beta HCG", LabUnit.INTERNATIONAL_UNITS_PER_LITER),
    HCO3_A("HCO3_A", "Act. bicarbonate", LabUnit.MILLIMOLES_PER_LITER),
    HCO3_A_BG("HCO3_A_BG", "Act. bicarbonate (blood gas)", LabUnit.MILLIMOLES_PER_LITER),
    HCO3_S_BG("HCO3_S_BG", "Standard bicarbonate (blood gas)", LabUnit.MILLIMOLES_PER_LITER),
    HDL("HDL", "HDL cholesterol", LabUnit.MILLIMOLES_PER_LITER),
    HEM_I("HEM_I", "Hemolysis index", LabUnit.NONE),
    HFC_LQ("HFC_LQ", "High fluorescent cells in liquor", LabUnit.MILLIONS_PER_LITER),
    HEMATOCRIT("Ht", "Hematocrit", LabUnit.NONE),
    I_O2_F("I_O2_F", "Fraction of inhaled oxygen", LabUnit.PERCENTAGE),
    INDIRECT_BILIRUBIN("IBIL", "Indirect bilirubin", LabUnit.MICROMOLES_PER_LITER),
    IONIZED_CALCIUM("ICA", "Ionized calcium (blood gas)", LabUnit.MILLIMOLES_PER_LITER),
    IONIZED_CALCIUM_74("ICA_74", "Ionized calcium 7.4 (blood gas)", LabUnit.MILLIMOLES_PER_LITER),
    ICSY("ICSY", "ENA EliA-Symphony antibodies", LabUnit.NONE),
    ICT_I("ICT_I", "Icteric index", LabUnit.NONE),
    IgA("IgA", "IgA", LabUnit.GRAMS_PER_LITER),
    IGF1("IGF1", "IGF-1", LabUnit.NANOMOLES_PER_LITER),
    IGF1_SDS("IGF1_SDS", "IGF-1 SDS", LabUnit.NONE),
    IgG("IgG", "IgG", LabUnit.GRAMS_PER_LITER),
    IgG4("IgG4", "Subclass IgG4", LabUnit.GRAMS_PER_LITER),
    IgM("IgM", "IgM", LabUnit.GRAMS_PER_LITER),
    IMALB_BL("IMALB_BL", "Immuno_chem ALB in BL", LabUnit.GRAMS_PER_LITER),
    IMMGRA_ABS("IMMGRA_ABS", "Immature granulocytes absolute", LabUnit.BILLIONS_PER_LITER),
    IMMGRA_PCT("IMMGRA_PCT", "Immature granulocytes percentage", LabUnit.PERCENTAGE),
    INTERNATIONAL_NORMALIZED_RATIO("INR", "International normalized ratio", LabUnit.NONE),
    INS("INS", "Insulin", LabUnit.PICOMOLES_PER_LITER),
    POTASSIUM("K", "Potassium", LabUnit.MILLIMOLES_PER_LITER),
    POTASSIUM_U("K_U", "Potassium in urine", LabUnit.MILLIMOLES_PER_LITER),
    LACT("LACT", "Lactate (blood gas)", LabUnit.MILLIMOLES_PER_LITER),
    LACTATE_DEHYDROGENASE("LDH", "Lactate dehydrogenase", LabUnit.UNITS_PER_LITER),
    LACTATE_DEHYDROGENASE_LQ("LDH_LQ", "Lactate dehydrogenase in liquor", LabUnit.UNITS_PER_LITER),
    LDL("LDL", "LDL cholesterol", LabUnit.MILLIMOLES_PER_LITER),
    LEUKOCYTES_ABS("LEUKO_ABS", "Leukocytes absolute", LabUnit.BILLIONS_PER_LITER),
    LH("LH", "Luteinizing hormone", LabUnit.UNITS_PER_LITER),
    LI_U("LI_U", "Lithium in urine", LabUnit.MILLIMOLES_PER_LITER),
    LIP_I("LIP_I", "Lipemic index", LabUnit.NONE),
    LIPASE("LIPA", "Lipase", LabUnit.UNITS_PER_LITER),
    LYMPHOCYTES_ABS("LYMPHO_ABS", "Lymphocytes absolute", LabUnit.BILLIONS_PER_LITER),
    LYMPHO_PCT("LYMPHO_PCT", "Lymphocytes percentage", LabUnit.PERCENTAGE),
    MB("MB", "Myoglobin", LabUnit.NANOMOLES_PER_LITER),
    MCH("MCH", "Mean corpuscular hemoglobin", LabUnit.FEMTOMOLES),
    MCHC("MCHC", "Mean corpuscular hemoglobin concentration", LabUnit.MILLIMOLES_PER_LITER),
    MCV("MCV", "Mean corpuscular volume", LabUnit.FEMTOLITERS),
    META("META", "Metanephrine ", LabUnit.NANOMOLES_PER_LITER),
    MAGNESIUM("Mg", "Magnesium", LabUnit.MILLIMOLES_PER_LITER),
    MHb("MHb", "Methemoglobin", LabUnit.NONE),
    MHb_F("MHb_F", "MetHb (blood gas) (F)", LabUnit.NONE),
    MHb_PCT("MHb_PCT", "MetHb (blood gas) (%)", LabUnit.PERCENTAGE),
    MNC("MNC", "Mononuclear cell", LabUnit.MILLIONS_PER_LITER),
    MOFC("MOFC", "Mycophenolat", LabUnit.MILLIGRAMS_PER_LITER),
    MONO_ABS("MONO_ABS", "Monocytes absolute", LabUnit.BILLIONS_PER_LITER),
    MONO_PCT("MONO_PCT", "Monocytes percentage", LabUnit.PERCENTAGE),
    MPV("MPV", "MPV", LabUnit.FEMTOLITERS),
    MYELO_ABS("MYELO_ABS", "Myelocytes absolute", LabUnit.BILLIONS_PER_LITER),
    MYELO_PCT("MYELO_PCT", "Myelocytes percentage", LabUnit.PERCENTAGE),
    SODIUM("Na", "Sodium", LabUnit.MILLIMOLES_PER_LITER),
    Na_U("Na_U", "Sodium (urine)", LabUnit.MILLIMOLES_PER_LITER),
    NEUTROPHILS_ABS("NEUTRO_ABS", "Neutrophil granulocytes absolute", LabUnit.BILLIONS_PER_LITER),
    NEUTRO_PCT("NEUTRO_PCT", "Neutrophil granulocytes percentage", LabUnit.PERCENTAGE),
    NK_PCT("NK_PCT", "Percentage NK-cells", LabUnit.PERCENTAGE_OF_LEUKOCYTES),
    NMETA("NMETA", "Normetanephrine", LabUnit.NANOMOLES_PER_LITER),
    NON_HDL("NON_HDL", "Non-HDL cholesterol", LabUnit.NONE),
    NSE("NSE", "Neuron-specific enolase", LabUnit.MICROGRAMS_PER_LITER),
    O2_C_BG("O2_C_BG", "O2 content (blood gas)", LabUnit.MILLIMOLES_PER_LITER),
    O2_F_BG("O2_F_BG", "O2 saturation (blood gas) (F)", LabUnit.NONE),
    O2_SATURATION_BG("O2_S_BG", "O2 saturation (blood gas) (%)", LabUnit.PERCENTAGE),
    OP17("OP17", "17-OH Progesterone", LabUnit.NANOMOLES_PER_LITER),
    OSMO("OSMO", "Osmolality", LabUnit.MILLI_OSMOLE_PER_KILOGRAM),
    OSMO_U("OSMO_U", "Osmolality in urine", LabUnit.MILLI_OSMOLE_PER_KILOGRAM),
    p50_BG("p50_BG", "P50 (blood gas)", LabUnit.KILO_PASCAL),
    pCO2_BG("pCO2_BG", "pCO2 (blood gas)", LabUnit.KILO_PASCAL),
    PCT("PCT", "Procalcitonin", LabUnit.NANOGRAMS_PER_MILLILITER),
    PFAE("PFAE", "PFA-Col/EPI", LabUnit.SECONDS),
    pH_BG("pH_BG", "pH (blood gas)", LabUnit.NONE),
    pH_OV("pH_OV", "pH OV", LabUnit.NONE),
    pH_U("pH_U", "pH urine strip", LabUnit.NONE),
    PHOSPHATE("PHOS", "Phosphate", LabUnit.MILLIMOLES_PER_LITER),
    PLASMA_PCT("PLASMA_PCT", "Percentage plasma cells", LabUnit.PERCENTAGE_OF_LEUKOCYTES),
    PNC("PNC", "Polynuclear cells", LabUnit.MILLIONS_PER_LITER),
    pO2_BG("pO2_BG", "pO2 (blood gas)", LabUnit.KILO_PASCAL),
    PREC_BCELL_PCT("PREC_BCELL_PCT", "% precursor-B-cells", LabUnit.PERCENTAGE_OF_LEUKOCYTES),
    PREC_MYL_PCT("PREC_MYL_PCT", "% myeloid precursor-cells", LabUnit.PERCENTAGE_OF_LEUKOCYTES),
    PRG("PRG", "Progesterone", LabUnit.NANOMOLES_PER_LITER),
    PRL("PRL", "Prolactin", LabUnit.UNITS_PER_LITER),
    PRNT50_SARS_CoV_2("PRNT50_SARS_CoV_2", "PRNT50 SARS-CoV-2", LabUnit.PRNT50),
    PSA("PSA", "Prostate-specific antigen", LabUnit.MICROGRAMS_PER_LITER),
    PSA_R("PSA_R", "Ratio PSA", LabUnit.PERCENTAGE),
    PROTHROMBIN_TIME("PT", "Prothrombin time", LabUnit.SECONDS),
    PTH("PTH", "Parathyroid hormone intact", LabUnit.PICOMOLES_PER_LITER),
    RDW("RDW", "Relative distribution width", LabUnit.PERCENTAGE),
    RETI_ABS("RETI_ABS", "Reticulocytes absolute", LabUnit.BILLIONS_PER_LITER),
    RETI_I("RETI_I", "Reticulocyte index", LabUnit.PERCENTAGE),
    ROD_ABS("ROD_ABS", "Rod-shaped granulocytes absolute", LabUnit.BILLIONS_PER_LITER),
    ROD_PCT("ROD_PCT", "Rod-shaped granulocytes percentage", LabUnit.PERCENTAGE),
    RT3("RT3", "Reverse-T3", LabUnit.NANOMOLES_PER_LITER),
    SCC("SCC", "Squamous cell carcinoma antigen", LabUnit.MICROGRAMS_PER_LITER),
    SEG_ABS("SEG_ABS", "Segments absolute", LabUnit.BILLIONS_PER_LITER),
    SEG_PCT("SEG_PCT", "Segments percentage", LabUnit.PERCENTAGE),
    SEROT("SEROT", "Serotonin", LabUnit.MICROMOLES_PER_LITER),
    SHBG("SHBG", "SHBG", LabUnit.NANOMOLES_PER_LITER),
    SmIgK_SmIgL_R("SmIgK_SmIgL_R", "SmIgK/SmIgL ratio", LabUnit.NONE),
    SOL_IL2R("SOL_IL2R", "Soluble IL-2R", LabUnit.UNITS_PER_MILLILITER),
    SSAQ("SSAQ", "SS-A antibodies", LabUnit.UNITS_PER_MILLILITER),
    SSBQ("SSBQ", "SS-B antibodies", LabUnit.UNITS_PER_MILLILITER),
    SWEIGHT("SWEIGHT", "Specific weight", LabUnit.KILOGRAMS_PER_LITER),
    BOUND_T3("T3", "Bound T3", LabUnit.NANOMOLES_PER_LITER),
    T3_REF("T3_REF", "Triiodothyronine (Ref)", LabUnit.NANOMOLES_PER_LITER),
    T4("T4", "T4", LabUnit.NANOMOLES_PER_LITER),
    TACROLIMUS("TACR", "Tacrolimus", LabUnit.MICROGRAMS_PER_LITER),
    TOTAL_BILIRUBIN("TBIL", "Total bilirubin", LabUnit.MICROMOLES_PER_LITER),
    TCELL_ABS("TCELL_ABS", "T-Cells absolute", LabUnit.MILLIONS_PER_LITER),
    TCELL_PCT("TCELL_PCT", "Percentage T-cells", LabUnit.PERCENTAGE_OF_LEUKOCYTES),
    TCI("TCI", "Thrombo citrate", LabUnit.BILLIONS_PER_LITER),
    TG("TG", "hs-Thyreoglobulin", LabUnit.MICROGRAMS_PER_LITER),
    TG_AB("TG_AB", "hs-Thyreoglobulin antibody", LabUnit.UNITS_PER_MILLILITER),
    TG_REC("TG_REC", "hs-Thyreoglobulin recovery", LabUnit.PERCENTAGE),
    THROMBOCYTES_ABS("THROMBO_ABS", "Absolute thrombocyte count", LabUnit.BILLIONS_PER_LITER),
    TP("TP", "Total protein", LabUnit.GRAMS_PER_LITER),
    TP_LQ("TP_LQ", "Total protein in liquor", LabUnit.GRAMS_PER_LITER),
    TOTAL_PROTEIN_URINE("TP_U", "Total protein in urine", LabUnit.GRAMS_PER_LITER),
    TP_U_KR("TP_U_KR", "Total protein urine/creatinine", LabUnit.MILLIGRAMS_PER_MILLIMOLE),
    TP_U_KR_R("TP_U_KR_R", "Urine protein to creatinine ratio", LabUnit.NONE),
    TRAF("TRAF", "Transferrin", LabUnit.GRAMS_PER_LITER),
    TRIGLYCERIDE("TRIGLY", "Triglyceride", LabUnit.MILLIMOLES_PER_LITER),
    TROPONIN_I_T("HSTNT", "Troponin I and T", LabUnit.NANOGRAMS_PER_LITER),
    TSAT("TSAT", "Transferrin saturation", LabUnit.PERCENTAGE),
    THYROID_STIMULATING_HORMONE("TSH", "Thyroid stimulating hormone", LabUnit.MILLIUNITS_PER_LITER),
    TSN("TSN", "Testosterone", LabUnit.NANOMOLES_PER_LITER),
    TSN_FREE("TSN_FREE", "Free testosterone", LabUnit.NANOMOLES_PER_LITER),
    U_SG("U_SG", "Urine specific gravity", LabUnit.NONE),
    URAC("URAC", "Uric acid", LabUnit.MILLIMOLES_PER_LITER),
    UREA("UREA", "Urea", LabUnit.MILLIMOLES_PER_LITER),
    UREA_U("UREA_U", "Urea in urine", LabUnit.MILLIMOLES_PER_LITER),
    UROB_U("UROB_U", "Urobilinogen in urine", LabUnit.MICROMOLES_PER_LITER),
    VITAMIN_A("VIT_A", "Vitamin A", LabUnit.MICROMOLES_PER_LITER),
    VITAMIN_B12("VIT_B12", "Vitamin B12", LabUnit.PICOMOLES_PER_LITER),
    VITAMIN_D_1_25_DI_OH("VIT_D_1_25_DI_OH", "1.25-di-OH Vitamin D", LabUnit.PICOMOLES_PER_LITER),
    VITAMIN_D_25_OH("VIT_D_25_OH", "Vitamin D 25-OH", LabUnit.NANOMOLES_PER_LITER),
    VITAMIN_E("VIT_E", "Vitamin E blood", LabUnit.MICROMOLES_PER_LITER),
    VITAMIN_K("VIT_K", "Vitamin K", LabUnit.NANOMOLES_PER_LITER),
    VWF_ACT("VWF_ACT", "vWF act", LabUnit.UNITS_PER_MILLILITER),
    VWF_AG("VWF_AG", "vWF antigen", LabUnit.UNITS_PER_MILLILITER),
    VWF_CBA("VWF_CBA", "vWF collagen binding", LabUnit.UNITS_PER_MILLILITER),
    WBC("WBC", "Leukocytes", LabUnit.MILLIONS_PER_LITER),
    WBC_LQ("WBC_LQ", "Leukocytes in liquor", LabUnit.BILLIONS_PER_LITER),
    WBCC("WBCC", "White blood cell count", LabUnit.MILLIONS_PER_MILLILITER),
    WRR("WRR", "White blood cell / Red blood cell ratio LQ", LabUnit.PERCENTAGE),
    ZINC("Zn", "Zinc in whole blood", LabUnit.MICROMOLES_PER_LITER),
    UNKNOWN("UNKNOWN", "unknown", LabUnit.NONE);

    override fun display(): String {
        return display
    }
}
