package com.hartwig.actin.treatment.input.single;

public enum FunctionInput {
    NONE,
    ONE_INTEGER,
    TWO_INTEGERS,
    ONE_DOUBLE,
    TWO_DOUBLES,
    ONE_TREATMENT,
    ONE_TREATMENT_ONE_INTEGER,
    ONE_TYPED_TREATMENT_MANY_STRINGS,
    ONE_TYPED_TREATMENT_MANY_STRINGS_ONE_INTEGER,
    ONE_TUMOR_TYPE,
    ONE_STRING,
    ONE_STRING_ONE_INTEGER,
    TWO_STRINGS,
    MANY_STRINGS_ONE_INTEGER,
    MANY_STRINGS_TWO_INTEGERS,
    MANY_TREATMENTS_MANY_STRINGS,
    ONE_INTEGER_ONE_STRING,
    ONE_INTEGER_MANY_STRINGS,
    ONE_TUMOR_STAGE,
    ONE_HLA_ALLELE,
    ONE_DOID_TERM
}
