report.title=Hartwig Trial Search RUO Report
footer.research.disclaimer=All results and data described in this report are for Research Use Only and have not been generated \
  using a clinically validated and controlled procedure nor is it a validated medical device. \
  The results should not be used for diagnostic or treatment purposes. \
  No rights can be derived from the content of this report.
