package com.hartwig.actin.algo.doid

object DoidConstants {
    const val CANCER_DOID = "162"
    const val ORGAN_SYSTEM_CANCER_DOID = "0050686"
    const val LIVER_CANCER_DOID = "3571"
    const val CNS_CANCER_DOID = "3620"
    const val BRAIN_CANCER_DOID = "1319"
    const val LUNG_CANCER_DOID = "1324"
    const val LUNG_CARCINOMA_DOID = "3905"
    const val LUNG_SQUAMOUS_CELL_CARCINOMA_DOID = "3907"
    const val LUNG_ADENOSQUAMOUS_CARCINOMA_DOID = "4829"
    const val LUNG_NON_SMALL_CELL_CARCINOMA_DOID = "3908"
    const val LUNG_NON_SQUAMOUS_NON_SMALL_CARCINOMA_DOID = "0080521"
    const val LUNG_ADENOCARCINOMA_DOID = "3910"
    const val LUNG_LARGE_CELL_CARCINOMA_DOID = "4556"
    const val LUNG_SARCOMA = "10124"
    const val BONE_CANCER_DOID = "184"
    const val PROSTATE_CANCER_DOID = "10283"
    const val STOMACH_CANCER_DOID = "10534"
    const val BREAST_CANCER_DOID = "1612"
    const val OVARIAN_CANCER_DOID = "2394"
    const val HEAD_AND_NECK_CANCER_DOID = "11934"
    const val COLORECTAL_CANCER_DOID = "9256"
    const val GLIOBLASTOMA_DOID = "3068"
    const val BENIGN_NEOPLASM_DOID = "0060072"
    const val HER2_NEGATIVE_BREAST_CANCER_DOID = "0060080"
    const val PROGESTERONE_POSITIVE_BREAST_CANCER_DOID = "0060077"
    const val ESTROGEN_POSITIVE_BREAST_CANCER_DOID = "0060075"
    const val HER2_POSITIVE_BREAST_CANCER_DOID = "0060079"
    const val PROGESTERONE_NEGATIVE_BREAST_CANCER_DOID = "0060078"
    const val ESTROGEN_NEGATIVE_BREAST_CANCER_DOID = "0060076"
    const val TRIPLE_NEGATIVE_BREAST_CANCER_DOID = "0060081"
    const val OVARIAN_MUCINOUS_MALIGNANT_ADENOFIBROMA_DOID = "6278"
    const val OVARIAN_MUCINOUS_CYSTADENOFIBROMA_DOID = "7013"
    const val MUCINOUS_OVARIAN_CYSTADENOMA_DOID = "3267"
    const val OVARIAN_MUCINOUS_CYSTADENOCARCINOMA_DOID = "3604"
    const val OVARIAN_MUCINOUS_ADENOCARCINOMA_DOID = "3606"
    const val OVARIAN_MUCINOUS_NEOPLASM_DOID = "6067"
    const val OVARIAN_MUCINOUS_ADENOFIBROMA_DOID = "6469"
    const val OVARIAN_SEROMUCINOUS_CARCINOMA_DOID = "6898"
    const val PROSTATE_SMALL_CELL_CARCINOMA_DOID = "7141"
    const val PROSTATE_NEUROENDOCRINE_NEOPLASM = "2992"
    const val SARCOMA_DOID = "1115"
    const val MUCINOUS_ADENOCARCINOMA_DOID = "3030"
    const val SMALL_CELL_CARCINOMA_DOID = "0050685"
    const val NEUROENDOCRINE_TUMOR_DOID = "169"
    const val NEUROENDOCRINE_CARCINOMA_DOID = "1800"
    const val RECTUM_NEUROENDOCRINE_NEOPLASM_DOID = "5777"
    const val LEUKEMIA_DOID = "1240"
    const val HEMATOLOGIC_CANCER_DOID = "2531"
    const val REFRACTORY_HEMATOLOGIC_CANCER_DOID = "712"
    const val CENTRAL_NERVOUS_SYSTEM_HEMATOLOGIC_CANCER_DOID = "5772"
    const val BONE_MARROW_CANCER_DOID = "4960"
    const val LYMPHOMA_DOID = "0060058"
    const val LYMPH_NODE_CANCER_DOID = "10619"
    const val MULTIPLE_MYELOMA_DOID = "9538"
    const val DENDRITIC_CELL_THYMOMA_DOID = "3282"
    const val HISTIOCYTIC_AND_DENDRITIC_CELL_CANCER_DOID = "5621"
    const val MAST_CELL_NEOPLASM_DOID = "3664"
    const val MYELOID_SARCOMA_DOID = "8683"
    const val KIDNEY_DISEASE_DOID = "557"
    const val GASTROINTESTINAL_SYSTEM_DISEASE_DOID = "77"
    const val LONG_QT_SYNDROME_DOID = "2843"
    const val PNEUMONITIS_DOID = "2797"
    const val DRUG_ALLERGY_DOID = "0060500"
    const val HEPATITIS_A_DOID = "12549"
    const val HEPATITIS_B_DOID = "2043"
    const val HEPATITIS_C_DOID = "1883"
    const val HIV_DOID = "526"
    const val CYTOMEGALOVIRUS_DOID = "0080827"
    const val TUBERCULOSIS_DOID = "399"
    const val AUTOSOMAL_DOMINANT_HYPOCALCEMIA_DOID = "0090109"
    const val PRIMARY_HYPOMAGNESEMIA_DOID = "0060879"
    const val HYPOKALEMIA_DOID = "4500"
    const val AUTOIMMUNE_DISEASE_DOID = "417"
    const val CARDIOVASCULAR_DISEASE_DOID = "1287"
    const val CENTRAL_NERVOUS_SYSTEM_DOID = "331"
    const val DIABETES_DOID = "9351"
    const val EYE_DISEASE_DOID = "5614"
    const val GASTROINTESTINAL_DISEASE_DOID = "77"
    const val GILBERT_DISEASE_DOID = "2739"
    const val HEART_DISEASE_DOID = "114"
    const val CORONARY_ARTERY_DISEASE_DOID = "3393"
    const val HYPERTENSION_DOID = "10763"
    const val IMMUNE_SYSTEM_DISEASE_DOID = "2914"
    const val INTERSTITIAL_LUNG_DISEASE_DOID = "3082"
    const val LUNG_DISEASE_DOID = "850"
    const val LIVER_DISEASE_DOID = "409"
    const val LIVER_CIRRHOSIS_DOID = "5082"
    const val MYOCARDIAL_INFARCT_DOID = "5844"
    const val STROKE_DOID = "6713"
    const val VASCULAR_DISEASE_DOID = "178"
    const val AUTOSOMAL_HEMOPHILIA_A_DOID = "0111823"
    const val HEMOPHILIA_B_DOID = "12259"
    const val VON_WILLEBRANDS_DISEASE_DOID = "12531"
    const val FACTOR_V_DEFICIENCY_DOID = "2216"
    const val PROTEIN_C_DEFICIENCY_DOID = "3756"
    const val PROTEIN_S_DEFICIENCY_DOID = "2451"
    const val ANTITHROMBIN_III_DEFICIENCY_DOID = "3755"
    const val THROMBOSIS_DOID = "0060903"
    const val PULMONARY_EMBOLISM_DOID = "9477"
    const val ENDOMETRIAL_SMALL_CELL_CARCINOMA_DOID = "7139"
    const val LUNG_COMBINED_TYPE_SMALL_CELL_ADENOCARCINOMA_DOID = "0050917"
    const val BLADDER_SMALL_CELL_CARCINOMA_DOID = "0080902"
    const val SMALL_CELL_SARCOMA_DOID = "3098"
    const val SMALL_CELL_OSTEOGENIC_SARCOMA_DOID = "3377"
    const val LUNG_SMALL_CELL_CARCINOMA_DOID = "5409"
    const val LUNG_OCCULT_SMALL_CELL_CARCINOMA_DOID = "5414"
    const val LUNG_COMBINED_TYPE_SMALL_CELL_CARCINOMA_DOID = "5421"
    const val EXTRAHEPATIC_BILE_DUCT_SMALL_CELL_ADENOCARCINOMA_DOID = "5926"
    const val OVARIAN_SMALL_CELL_CARCINOMA_DOID = "6179"
    const val GASTRIC_SMALL_CELL_CARCINOMA_DOID = "6552"
    const val COLON_SMALL_CELL_CARCINOMA_DOID = "6727"
    const val CERVIX_SMALL_CELL_CARCINOMA_DOID = "6740"
    const val URETER_SMALL_CELL_CARCINOMA_DOID = "6886"
    const val LUNG_MIXED_SMALL_CELL_AND_SQUAMOUS_CELL_CARCINOMA_DOID = "7081"
    const val URINARY_BLADDER_SMALL_CELL_NEUROENDOCRINE_CARCINOMA_DOID = "7132"
    const val GALLBLADDER_SMALL_CELL_CARCINOMA_DOID = "7133"
    const val ESOPHAGUS_SMALL_CELL_CARCINOMA_DOID = "7134"
    const val AMPULLA_OF_VATER_SMALL_CELL_CARCINOMA_DOID = "7136"
    const val BARTHOLINS_GLAND_SMALL_CELL_CARCINOMA_DOID = "7140"
    const val THYMUS_SMALL_CELL_CARCINOMA_DOID = "7142"
    const val LARYNGEAL_SMALL_CELL_CARCINOMA_DOID = "7144"
    const val PULMONARY_TYPE_OVARIAN_SMALL_CELL_CARCINOMA_DOID = "7650"
    const val SMALL_CELL_CARCINOMA_OF_THE_OVARY_OF_HYPERCALCEMIC_TYPE_DOID = "7651"
    const val BRONCHIOLITIS_DOID = "2942"
    const val BRONCHOPULMONARY_DYSPLASIA_DOID = "11650"
    const val GRANULOMATOSIS_WITH_POLYANGIITIS_DOID = "12132"
    const val INVASIVE_ASPERGILLOSIS_DOID = "0050073"
    const val LUNG_ABSCESS_DOID = "0060317"
    const val OBSTRUCTIVE_LUNG_DISEASE_DOID = "2320"
    const val PNEUMONIA_DOID = "552"
    const val PULMONARY_ARTERY_DISEASE_DOID = "60001"
    const val RESPIRATORY_FAILURE_DOID = "11162"
    const val GASTROINTESTINAL_AUTOIMMUNE_DISEASE_DOID = "0060031"
    const val INFLAMMATORY_BOWEL_DISEASE_DOID = "0050589"
    const val CELIAC_DISEASE_DOID = "10608"
    const val DIARRHEA_DOID = "13250"
    const val GASTROINTESTINAL_ALLERGY_DOID = "0060502"
    const val ESOPHAGEAL_DISEASE_DOID = "6050"
    const val INTESTINAL_PSEUDO_OBSTRUCTION_DOID = "0080072"
    const val MEGACOLON_DOID = "11372"
    const val DIVERTICULITIS_DOID = "7475"
    const val DUODENITIS_DOID = "8643"
    const val DUODENAL_OBSTRUCTION_DOID = "3558"
    const val INTESTINAL_ATRESIA_DOID = "10486"
    const val INTESTINAL_INFECTIOUS_DISEASE_DOID = "100"
    const val INTESTINAL_OBSTRUCTION_DOID = "8437"
    const val INTESTINAL_PERFORATION_DOID = "2074"
    const val POSTGASTRECTOMY_SYNDROME_DOID = "8439"
    const val GASTROENTERITIS_DOID = "2326"
    const val PANCREAS_DISEASE_DOID = "26"
    const val BILIARY_TRACT_DISEASE_DOID = "9741"
    const val PROTEIN_LOSING_ENTEROPATHY_DOID = "10611"
    const val SHORT_BOWEL_SYNDROME_DOID = "10605"
    const val STOMACH_DISEASE_DOID = "76"

    val THROMBOEMBOLIC_EVENT_DOID_SET = setOf(THROMBOSIS_DOID, PULMONARY_EMBOLISM_DOID, MYOCARDIAL_INFARCT_DOID, STROKE_DOID)

    val LUNG_CANCER_DOID_SET = setOf(
        LUNG_SQUAMOUS_CELL_CARCINOMA_DOID,
        LUNG_ADENOSQUAMOUS_CARCINOMA_DOID,
        LUNG_NON_SMALL_CELL_CARCINOMA_DOID,
        LUNG_NON_SQUAMOUS_NON_SMALL_CARCINOMA_DOID,
        LUNG_ADENOCARCINOMA_DOID,
        LUNG_LARGE_CELL_CARCINOMA_DOID,
        LUNG_CANCER_DOID,
        LUNG_SMALL_CELL_CARCINOMA_DOID,
        LUNG_OCCULT_SMALL_CELL_CARCINOMA_DOID,
        LUNG_COMBINED_TYPE_SMALL_CELL_CARCINOMA_DOID,
        LUNG_MIXED_SMALL_CELL_AND_SQUAMOUS_CELL_CARCINOMA_DOID,
        LUNG_COMBINED_TYPE_SMALL_CELL_ADENOCARCINOMA_DOID,
        LUNG_CARCINOMA_DOID
    )

    val RESPIRATORY_COMPROMISE_DOID_SET = setOf(
        BRONCHIOLITIS_DOID,
        BRONCHOPULMONARY_DYSPLASIA_DOID,
        GRANULOMATOSIS_WITH_POLYANGIITIS_DOID,
        INTERSTITIAL_LUNG_DISEASE_DOID,
        INVASIVE_ASPERGILLOSIS_DOID,
        LUNG_ABSCESS_DOID,
        OBSTRUCTIVE_LUNG_DISEASE_DOID,
        PNEUMONIA_DOID,
        PULMONARY_ARTERY_DISEASE_DOID,
        RESPIRATORY_FAILURE_DOID
    )

    val SMALL_CELL_DOID_SET = setOf(
        PROSTATE_SMALL_CELL_CARCINOMA_DOID,
        SMALL_CELL_CARCINOMA_DOID,
        ENDOMETRIAL_SMALL_CELL_CARCINOMA_DOID,
        LUNG_COMBINED_TYPE_SMALL_CELL_ADENOCARCINOMA_DOID,
        BLADDER_SMALL_CELL_CARCINOMA_DOID,
        SMALL_CELL_SARCOMA_DOID,
        SMALL_CELL_OSTEOGENIC_SARCOMA_DOID,
        LUNG_SMALL_CELL_CARCINOMA_DOID,
        LUNG_OCCULT_SMALL_CELL_CARCINOMA_DOID,
        LUNG_COMBINED_TYPE_SMALL_CELL_CARCINOMA_DOID,
        EXTRAHEPATIC_BILE_DUCT_SMALL_CELL_ADENOCARCINOMA_DOID,
        OVARIAN_SMALL_CELL_CARCINOMA_DOID,
        GASTRIC_SMALL_CELL_CARCINOMA_DOID,
        COLON_SMALL_CELL_CARCINOMA_DOID,
        CERVIX_SMALL_CELL_CARCINOMA_DOID,
        URETER_SMALL_CELL_CARCINOMA_DOID,
        LUNG_MIXED_SMALL_CELL_AND_SQUAMOUS_CELL_CARCINOMA_DOID,
        URINARY_BLADDER_SMALL_CELL_NEUROENDOCRINE_CARCINOMA_DOID,
        GALLBLADDER_SMALL_CELL_CARCINOMA_DOID,
        ESOPHAGUS_SMALL_CELL_CARCINOMA_DOID,
        AMPULLA_OF_VATER_SMALL_CELL_CARCINOMA_DOID,
        BARTHOLINS_GLAND_SMALL_CELL_CARCINOMA_DOID,
        THYMUS_SMALL_CELL_CARCINOMA_DOID,
        LARYNGEAL_SMALL_CELL_CARCINOMA_DOID,
        PULMONARY_TYPE_OVARIAN_SMALL_CELL_CARCINOMA_DOID,
        SMALL_CELL_CARCINOMA_OF_THE_OVARY_OF_HYPERCALCEMIC_TYPE_DOID
    )
    val ABSORPTION_DIFFICULTIES_DOID_SET = setOf(
        GASTROINTESTINAL_AUTOIMMUNE_DISEASE_DOID,
        INFLAMMATORY_BOWEL_DISEASE_DOID,
        CELIAC_DISEASE_DOID,
        DIARRHEA_DOID,
        GASTROINTESTINAL_ALLERGY_DOID,
        ESOPHAGEAL_DISEASE_DOID,
        INTESTINAL_PSEUDO_OBSTRUCTION_DOID,
        MEGACOLON_DOID,
        DIVERTICULITIS_DOID,
        DUODENITIS_DOID,
        DUODENAL_OBSTRUCTION_DOID,
        INTESTINAL_ATRESIA_DOID,
        INTESTINAL_INFECTIOUS_DISEASE_DOID,
        INTESTINAL_OBSTRUCTION_DOID,
        INTESTINAL_PERFORATION_DOID,
        POSTGASTRECTOMY_SYNDROME_DOID,
        GASTROENTERITIS_DOID,
        PANCREAS_DISEASE_DOID,
        BILIARY_TRACT_DISEASE_DOID,
        PROTEIN_LOSING_ENTEROPATHY_DOID,
        SHORT_BOWEL_SYNDROME_DOID,
        STOMACH_DISEASE_DOID
    )
}