package com.hartwig.actin.treatment.datamodel;

public enum EligibilityRule {
    // Composite rules combining other rules.
    AND,
    OR,
    NOT,
    WARN_ON_PASS,

    // Rules based on general information and health of patient
    IS_AT_LEAST_18_YEARS_OLD,
    IS_BREASTFEEDING,
    IS_PREGNANT,
    HAS_LIFE_EXPECTANCY_OF_AT_LEAST_X_WEEKS,
    HAS_WHO_STATUS_OF_AT_MOST_X,
    HAS_HAD_SURGERY_WITHIN_LAST_X_WEEKS,

    // Rules based on pathology information
    PRIMARY_TUMOR_LOCATION_BELONGS_TO_DOID_X,

    // Rules based on radiology information
    HAS_ADVANCED_CANCER,
    HAS_METASTATIC_CANCER,
    HAS_LIVER_METASTASES,
    HAS_ACTIVE_CNS_METASTASES,
    HAS_MEASURABLE_DISEASE_RECIST,
    HAS_BIOPSY_AMENABLE_LESION,

    // Rules based on (cancer) treatment information
    HAS_EXHAUSTED_SOC_TREATMENTS,
    HAS_DECLINED_SOC_TREATMENTS,
    HAS_HAD_MAX_X_NR_ANTI_PD_L1_OR_PD_1_IMMUNOTHERAPIES,
    HAS_HISTORY_OF_SECOND_MALIGNANCY,
    SECOND_MALIGNANCY_HAS_BEEN_CURED_SINCE_X_YEARS,

    // Rules based on laboratory data
    HAS_LEUKOCYTES_ABS_OF_AT_LEAST_X,
    HAS_HEMOGLOBIN_G_PER_DL_OF_AT_LEAST_X,
    HAS_THROMBOCYTES_ABS_AT_LEAST_X,
    HAS_CREATININE_ULN_OF_AT_MOST_X,
    HAS_CREATININE_CLEARANCE_CKD_EPI_OF_AT_LEAST_X,
    HAS_TOTAL_BILIRUBIN_ULN_AT_MOST_X,
    HAS_DIRECT_BILIRUBIN_ULN_AT_MOST_X,
    HAS_ASAT_ULN_OF_AT_MOST_X,
    HAS_INR_ULN_AT_MOST_X,
    HAS_PT_ULN_AT_MOST_X,
    HAS_APTT_ULN_AT_MOST_X,

    // Rules based on other conditions
    HAS_ACTIVE_INFECTION,
    HAS_SIGNIFICANT_CONCOMITANT_ILLNESS,
    HAS_HISTORY_OF_AUTOIMMUNE_DISEASE,
    HAS_HISTORY_OF_CARDIAC_DISEASE,
    HAS_KNOWN_HEPATITIS_B_INFECTION,
    HAS_KNOWN_HEPATITIS_C_INFECTION,
    HAS_KNOWN_HIV_INFECTION,
    HAS_GILBERT_DISEASE,

    // Rules related to current medication
    HAS_ALLERGY_RELATED_TO_STUDY_MEDICATION,
    HAS_STABLE_ANTICOAGULANT_DOSING,
    HAS_TOXICITY_OF_AT_LEAST_GRADE_X,
    HAS_TOXICITY_OF_AT_LEAST_GRADE_X_IN_NEUROPATHY,
    CURRENTLY_GETS_IMMUNOSUPPRESSANT_MEDICATION,
    CURRENTLY_GETS_CORTICOSTEROID_MEDICATION,

    // Rules related to blood pressure information
    HAS_SBP_MMHG_OF_AT_LEAST_X,
    HAS_DBP_MMHG_OF_AT_LEAST_X,

    // Rules related to blood transfusions
    HAS_HAD_ERYTHROCYTE_TRANSFUSION_WITHIN_LAST_X_WEEKS,
    HAS_HAD_THROMBOCYTE_TRANSFUSION_WITHIN_LAST_X_WEEKS
}
